import Head from 'next/head';
import React from 'react'
import { Container, Nav, Navbar } from 'react-bootstrap'
import { IHeader } from '../Language/HomePage/Header';
import {Spanish, English} from '../Language/Languages';

interface Props{
    useLanguage:[
        {
            Home: {
                Header: IHeader;
            };
        },
        React.Dispatch<React.SetStateAction<{
            Home: {
                Header: IHeader;
            };
        }>>
    ]
}
const Header :React.FC<Props> = ({useLanguage}) => {
  const [Language, setLanguage] = useLanguage;
  const {Home:{Header:{Header, Navigation}}} = Language;

  return(
    <>
        <Head>
            <title>{Header.PageTitle}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <header>
            <Navbar collapseOnSelect expand="lg" bg="dark" variant="dark">
                    <Container>
                    <Navbar.Brand href="#home">{Navigation.NavTitle}</Navbar.Brand>
                    <Navbar.Toggle aria-controls="responsive-navbar-nav" />
                    <Navbar.Collapse id="responsive-navbar-nav">
                        <Nav className="me-auto">
                            <Nav.Link href="#features">{Navigation.AboutPage}</Nav.Link>
                            <Nav.Link href="#pricing">{Navigation.News}</Nav.Link>
                            <Nav.Link href="#pricing">{Navigation.Support}</Nav.Link>
                            <Nav.Link href="#pricing">{Navigation.Documentation}</Nav.Link>
                        </Nav>
                        <Nav>
                            <Nav.Link href="#deets" onClick={()=>setLanguage(English)}>EN</Nav.Link>
                            <Nav.Link href="#deets" onClick={()=>setLanguage(Spanish)}>ES</Nav.Link>
                        </Nav>
                    </Navbar.Collapse>
                    </Container>
            </Navbar>
        </header>
    </>
  )
}

export default Header 

{/* <NavDropdown title="Dropdown" id="collasible-nav-dropdown">
                        <NavDropdown.Item href="#action/3.1">Action</NavDropdown.Item>
                        <NavDropdown.Item href="#action/3.2">Another action</NavDropdown.Item>
                        <NavDropdown.Item href="#action/3.3">Something</NavDropdown.Item>
                        <NavDropdown.Divider />
                        <NavDropdown.Item href="#action/3.4">Separated link</NavDropdown.Item>
                    </NavDropdown> */}