import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

interface Props{
  testerino:string;
}
const Home: NextPage<Props> = ({testerino}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Project Neisa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>{testerino}</p>
      <h1>Hello Neisa</h1>
    </div>
  )
}

export default Home
